// renderers/angular/src/lib/components/modal.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import {
  Component,
  signal,
  viewChild,
  ElementRef,
  effect,
  ChangeDetectionStrategy,
} from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Types } from '../types';
import { Renderer } from '../rendering';

@Component({
  selector: 'a2ui-modal',
  imports: [Renderer],
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    @if (showDialog()) {
      <dialog #dialog [class]="theme.components.Modal.backdrop" (click)="handleDialogClick($event)">
        <section [class]="theme.components.Modal.element" [style]="theme.additionalStyles?.Modal">
          <div class="controls">
            <button (click)="closeDialog()">
              <span class="g-icon">close</span>
            </button>
          </div>

          <ng-container
            a2ui-renderer
            [surfaceId]="surfaceId()!"
            [component]="component().properties.contentChild"
          />
        </section>
      </dialog>
    } @else {
      <section (click)="showDialog.set(true)">
        <ng-container
          a2ui-renderer
          [surfaceId]="surfaceId()!"
          [component]="component().properties.entryPointChild"
        />
      </section>
    }
  `,
  styles: `
    dialog {
      padding: 0;
      border: none;
      background: none;

      & section {
        & .controls {
          display: flex;
          justify-content: end;
          margin-bottom: 4px;

          & button {
            padding: 0;
            background: none;
            width: 20px;
            height: 20px;
            pointer: cursor;
            border: none;
            cursor: pointer;
          }
        }
      }
    }
  `,
})
export class Modal extends DynamicComponent<Types.ModalNode> {
  protected readonly showDialog = signal(false);
  protected readonly dialog = viewChild<ElementRef<HTMLDialogElement>>('dialog');

  constructor() {
    super();

    effect(() => {
      const dialog = this.dialog();

      if (dialog && !dialog.nativeElement.open) {
        dialog.nativeElement.showModal();
      }
    });
  }

  protected handleDialogClick(event: MouseEvent) {
    if (event.target instanceof HTMLDialogElement) {
      this.closeDialog();
    }
  }

  protected closeDialog() {
    const dialog = this.dialog();

    if (!dialog) {
      return;
    }

    if (!dialog.nativeElement.open) {
      dialog.nativeElement.close();
    }

    this.showDialog.set(false);
  }
}

// renderers/react/src/v0_9/catalog/basic/components/Modal.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState} from 'react';
import {createReactComponent} from '../../../adapter';
import {ModalApi} from '@a2ui/web-core/v0_9/basic_catalog';

export const Modal = createReactComponent(ModalApi, ({props, buildChild}) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <div onClick={() => setIsOpen(true)} style={{display: 'inline-block'}}>
        {props.trigger ? buildChild(props.trigger) : null}
      </div>
      {isOpen && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
          }}
          onClick={() => setIsOpen(false)}
        >
          <div
            style={{
              backgroundColor: '#fff',
              padding: '24px',
              borderRadius: '8px',
              maxWidth: '90%',
              maxHeight: '90%',
              overflow: 'auto',
              display: 'flex',
              flexDirection: 'column',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div style={{display: 'flex', justifyContent: 'flex-end'}}>
              <button
                onClick={() => setIsOpen(false)}
                style={{
                  border: 'none',
                  background: 'none',
                  fontSize: '20px',
                  cursor: 'pointer',
                  padding: '4px',
                }}
              >
                &times;
              </button>
            </div>
            <div style={{flex: 1}}>{props.content ? buildChild(props.content) : null}</div>
          </div>
        </div>
      )}
    </>
  );
});
