// renderers/angular/src/v0_8/components/checkbox.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Types } from '../types';

@Component({
  selector: 'a2ui-checkbox',
  template: `
    <label>
      <input
        type="checkbox"
        [id]="inputId"
        [checked]="inputChecked()"
        (change)="onToggle($event)"
      />
      {{ resolvedLabel() }}
    </label>
  `,
  styles: `
    :host {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Checkbox extends DynamicComponent<Types.CheckboxNode> {
  readonly label = input.required<Types.StringValue | null>();
  readonly value = input.required<Types.BooleanValue | null>();

  protected inputChecked = computed(() => super.resolvePrimitive(this.value()) ?? false);
  protected resolvedLabel = computed(() => super.resolvePrimitive(this.label()));
  protected readonly inputId = super.getUniqueId('a2ui-checkbox');

  onToggle(event: Event) {
    const checked = (event.target as HTMLInputElement).checked;
    this.sendAction({
      name: 'toggle',
      context: [{ key: 'checked', value: { literalBoolean: checked } }],
    });
  }
}

// renderers/lit/src/v0_9/catalogs/basic/components/CheckBox.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing } from "lit";
import { customElement } from "lit/decorators.js";
import { CheckBoxApi } from "@a2ui/web-core/v0_9/basic_catalog";
import { A2uiLitElement, A2uiController } from "@a2ui/lit/v0_9";

@customElement("a2ui-checkbox")
export class A2uiCheckBoxElement extends A2uiLitElement<typeof CheckBoxApi> {
  protected createController() {
    return new A2uiController(this, CheckBoxApi);
  }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    return html`
      <label class="a2ui-checkbox">
        <input
          type="checkbox"
          .checked=${props.value || false}
          @change=${(e: Event) =>
            props.setValue?.((e.target as HTMLInputElement).checked)}
        />
        ${props.label}
      </label>
    `;
  }
}

export const A2uiCheckBox = {
  ...CheckBoxApi,
  tagName: "a2ui-checkbox",
};
