// renderers/react/src/v0_9/catalog/basic/components/Row.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {createReactComponent} from '../../../adapter';
import {RowApi} from '@a2ui/web-core/v0_9/basic_catalog';
import {ChildList} from './ChildList';
import {mapJustify, mapAlign} from '../utils';

export const Row = createReactComponent(RowApi, ({props, buildChild, context}) => {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: mapJustify(props.justify),
        alignItems: mapAlign(props.align),
        width: '100%',
        margin: 0,
        padding: 0,
      }}
    >
      <ChildList childList={props.children} buildChild={buildChild} context={context} />
    </div>
  );
});

// renderers/lit/src/v0_9/catalogs/basic/components/Row.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing } from "lit";
import { customElement } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { styleMap } from "lit/directives/style-map.js";
import { RowApi } from "@a2ui/web-core/v0_9/basic_catalog";
import { A2uiLitElement, A2uiController } from "@a2ui/lit/v0_9";

@customElement("a2ui-basic-row")
export class A2uiBasicRowElement extends A2uiLitElement<typeof RowApi> {
  protected createController() {
    return new A2uiController(this, RowApi);
  }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    const children = Array.isArray(props.children) ? props.children : [];
    const styles = {
      display: "flex",
      flexDirection: "row",
      flex: props.weight !== undefined ? String(props.weight) : "initial",
      gap: "8px",
    };

    return html`
      <div class="a2ui-row" style=${styleMap(styles as Record<string, string>)}>
        ${map(children, (child: any) => html`${this.renderNode(child)}`)}
      </div>
    `;
  }
}

export const A2uiRow = {
  ...RowApi,
  tagName: "a2ui-basic-row",
};
