// renderers/angular/src/lib/components/modal.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import {
  Component,
  signal,
  viewChild,
  ElementRef,
  effect,
  ChangeDetectionStrategy,
} from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Types } from '../types';
import { Renderer } from '../rendering';

@Component({
  selector: 'a2ui-modal',
  imports: [Renderer],
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    @if (showDialog()) {
      <dialog #dialog [class]="theme.components.Modal.backdrop" (click)="handleDialogClick($event)">
        <section [class]="theme.components.Modal.element" [style]="theme.additionalStyles?.Modal">
          <div class="controls">
            <button (click)="closeDialog()">
              <span class="g-icon">close</span>
            </button>
          </div>

          <ng-container
            a2ui-renderer
            [surfaceId]="surfaceId()!"
            [component]="component().properties.contentChild"
          />
        </section>
      </dialog>
    } @else {
      <section (click)="showDialog.set(true)">
        <ng-container
          a2ui-renderer
          [surfaceId]="surfaceId()!"
          [component]="component().properties.entryPointChild"
        />
      </section>
    }
  `,
  styles: `
    dialog {
      padding: 0;
      border: none;
      background: none;

      & section {
        & .controls {
          display: flex;
          justify-content: end;
          margin-bottom: 4px;

          & button {
            padding: 0;
            background: none;
            width: 20px;
            height: 20px;
            pointer: cursor;
            border: none;
            cursor: pointer;
          }
        }
      }
    }
  `,
})
export class Modal extends DynamicComponent<Types.ModalNode> {
  protected readonly showDialog = signal(false);
  protected readonly dialog = viewChild<ElementRef<HTMLDialogElement>>('dialog');

  constructor() {
    super();

    effect(() => {
      const dialog = this.dialog();

      if (dialog && !dialog.nativeElement.open) {
        dialog.nativeElement.showModal();
      }
    });
  }

  protected handleDialogClick(event: MouseEvent) {
    if (event.target instanceof HTMLDialogElement) {
      this.closeDialog();
    }
  }

  protected closeDialog() {
    const dialog = this.dialog();

    if (!dialog) {
      return;
    }

    if (!dialog.nativeElement.open) {
      dialog.nativeElement.close();
    }

    this.showDialog.set(false);
  }
}

// renderers/react/src/v0_8/components/layout/Modal.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, useCallback, useRef, useEffect, memo} from 'react';
import type * as Types from '@a2ui/web-core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';
import {ComponentNode} from '../../core/ComponentNode';

/**
 * Modal component - displays content in a dialog overlay.
 *
 * Matches Lit's rendering approach:
 * - When closed: renders section with entry point child
 * - When open: renders dialog with content child (entry point is replaced)
 *
 * The dialog is rendered in place (no portal) so it stays inside .a2ui-surface
 * and CSS selectors work correctly. showModal() handles the top-layer overlay.
 */
export const Modal = memo(function Modal({node, surfaceId}: A2UIComponentProps<Types.ModalNode>) {
  const {theme} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const [isOpen, setIsOpen] = useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);

  const openModal = useCallback(() => {
    setIsOpen(true);
  }, []);

  const closeModal = useCallback(() => {
    setIsOpen(false);
  }, []);

  // Show dialog when isOpen becomes true, and sync state when dialog closes (e.g., via Escape)
  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    if (isOpen && !dialog.open) {
      dialog.showModal();
    }

    // Listen for native close event (triggered by Escape key)
    const handleClose = () => {
      setIsOpen(false);
    };
    dialog.addEventListener('close', handleClose);
    return () => dialog.removeEventListener('close', handleClose);
  }, [isOpen]);

  // Handle backdrop clicks (only close if clicking directly on dialog, not its content)
  const handleBackdropClick = useCallback(
    (e: React.MouseEvent<HTMLDialogElement>) => {
      if (e.target === e.currentTarget) {
        closeModal();
      }
    },
    [closeModal]
  );

  // Handle Escape key (for jsdom test compatibility - real browsers use native dialog behavior)
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLDialogElement>) => {
      if (e.key === 'Escape') {
        closeModal();
      }
    },
    [closeModal]
  );

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  // Match Lit's render approach: closed shows section with entry, open shows dialog
  if (!isOpen) {
    return (
      <div className="a2ui-modal" style={hostStyle}>
        <section onClick={openModal} style={{cursor: 'pointer'}}>
          <ComponentNode node={props.entryPointChild} surfaceId={surfaceId} />
        </section>
      </div>
    );
  }

  return (
    <div className="a2ui-modal" style={hostStyle}>
      <dialog
        ref={dialogRef}
        className={classMapToString(theme.components.Modal.backdrop)}
        onClick={handleBackdropClick}
        onKeyDown={handleKeyDown}
      >
        <section
          className={classMapToString(theme.components.Modal.element)}
          style={stylesToObject(theme.additionalStyles?.Modal)}
        >
          <div id="controls">
            <button onClick={closeModal} aria-label="Close modal">
              <span className="g-icon">close</span>
            </button>
          </div>
          <ComponentNode node={props.contentChild} surfaceId={surfaceId} />
        </section>
      </dialog>
    </div>
  );
});

export default Modal;
