// renderers/angular/src/v0_9/catalog/minimal/text-field.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ChangeDetectionStrategy, input, computed } from '@angular/core';
import { BoundProperty } from '../../core/types';


/**
 * Angular implementation of the A2UI TextField component (v0.9).
 */
@Component({
  selector: 'a2ui-v09-text-field',
  imports: [],
  template: `
    <div class="a2ui-text-field-container">
      @if (label()) {
        <label>{{ label() }}</label>
      }
      <input
        [type]="inputType()"
        [value]="value()"
        (input)="handleInput($event)"
        [placeholder]="placeholder()"
      />
      <!-- Validation errors would go here in a more advanced version -->
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        flex: 1;
        width: 100%;
      }
      .a2ui-text-field-container {
        display: flex;
        flex-direction: column;
        gap: 4px;
        margin: 4px;
      }
      input {
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextFieldComponent {
  /**
   * Bound properties.
   */
  props = input<Record<string, BoundProperty>>({});
  surfaceId = input<string>();
  componentId = input<string>();
  dataContextPath = input<string>();



  variant = computed(() => this.props()['variant']?.value());
  label = computed(() => this.props()['label']?.value());
  value = computed(() => this.props()['value']?.value() ?? '');
  placeholder = computed(() => this.props()['placeholder']?.value() ?? '');

  inputType = computed(() => {
    switch (this.variant()) {
      case 'obscured':
        return 'password';
      case 'number':
        return 'number';
      default:
        return 'text';
    }
  });

  handleInput(event: Event) {
    const value = (event.target as HTMLInputElement).value;
    // Update the data path.  If anything is listening to this path, it will be
    // notified.
    this.props()['value']?.onUpdate(value);
  }
}

// renderers/react/src/v0_9/catalog/minimal/components/TextField.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {z} from 'zod';
import {CommonSchemas} from '@a2ui/web-core/v0_9';

export const TextFieldSchema = z.object({
  label: CommonSchemas.DynamicString,
  value: CommonSchemas.DynamicString,
  variant: z.enum(['longText', 'number', 'shortText', 'obscured']).optional(),
  validationRegexp: z.string().optional(),
});

export const TextFieldApiDef = {
  name: 'TextField',
  schema: TextFieldSchema,
};

export const TextField = createReactComponent(TextFieldApiDef, ({props, context}) => {
  const onChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    if (props.setValue) {
      props.setValue(e.target.value);
    }
  };

  const isLong = props.variant === 'longText';
  const type =
    props.variant === 'number' ? 'number' : props.variant === 'obscured' ? 'password' : 'text';

  const style: React.CSSProperties = {
    padding: '8px',
    width: '100%',
    border: '1px solid #ccc',
    borderRadius: '4px',
    boxSizing: 'border-box',
  };

  const id = `textfield-${context.componentModel.id}`;

  return (
    <div style={{display: 'flex', flexDirection: 'column', gap: '4px', width: '100%'}}>
      {props.label && (
        <label htmlFor={id} style={{fontSize: '14px', fontWeight: 'bold'}}>
          {props.label}
        </label>
      )}
      {isLong ? (
        <textarea id={id} style={style} value={props.value || ''} onChange={onChange} />
      ) : (
        <input id={id} type={type} style={style} value={props.value || ''} onChange={onChange} />
      )}
    </div>
  );
});
