// renderers/react/src/v0_9/catalog/basic/components/Image.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {ImageApi} from '@a2ui/web-core/v0_9/basic_catalog';
import {getBaseLeafStyle} from '../utils';

export const Image = createReactComponent(ImageApi, ({props}) => {
  const mapFit = (fit?: string): React.CSSProperties['objectFit'] => {
    if (fit === 'scaleDown') return 'scale-down';
    return (fit as React.CSSProperties['objectFit']) || 'fill';
  };

  const style: React.CSSProperties = {
    ...getBaseLeafStyle(),
    objectFit: mapFit(props.fit),
    width: '100%',
    height: 'auto',
    display: 'block',
  };

  if (props.variant === 'icon') {
    style.width = '24px';
    style.height = '24px';
  } else if (props.variant === 'avatar') {
    style.width = '40px';
    style.height = '40px';
    style.borderRadius = '50%';
  } else if (props.variant === 'smallFeature') {
    style.maxWidth = '100px';
  } else if (props.variant === 'largeFeature') {
    style.maxHeight = '400px';
  } else if (props.variant === 'header') {
    style.height = '200px';
    style.objectFit = 'cover';
  }

  return <img src={props.url} alt={props.description || ''} style={style} />;
});

// renderers/angular/src/v0_9/catalog/basic/image.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';
import { BoundProperty } from '../../core/types';

/**
 * Angular implementation of the A2UI Image component (v0.9).
 *
 * Renders an image with configurable fit and shape variants.
 */
@Component({
  selector: 'a2ui-v09-image',
  standalone: true,
  imports: [],
  template: `
    <img
      [src]="url()"
      [alt]="description()"
      [style.object-fit]="fit()"
      [class]="'a2ui-image ' + variant()"
    />
  `,
  styles: [
    `
      .a2ui-image {
        display: block;
        max-width: 100%;
        height: auto;
      }
      .a2ui-image.icon {
        width: 24px;
        height: 24px;
      }
      .a2ui-image.avatar {
        border-radius: 50%;
        aspect-ratio: 1 / 1;
        width: 100px;
        height: 100px;
        margin: 0 auto;
      }
      .a2ui-image.smallFeature {
        max-width: 200px;
      }
      .a2ui-image.mediumFeature {
        max-width: 400px;
      }
      .a2ui-image.largeFeature {
        max-width: 800px;
      }
      .a2ui-image.header {
        width: 100%;
        max-height: 300px;
        object-fit: cover;
      }
      .a2ui-image.rounded {
        border-radius: 8px;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ImageComponent {
  /**
   * Reactive properties resolved from the A2UI {@link ComponentModel}.
   *
   * Expected properties:
   * - `url`: The absolute URL of the image.
   * - `description`: Accessibility text for the image.
   * - `fit`: Object-fit mode ('cover', 'contain', 'fill', 'none', 'scale-down').
   * - `variant`: Style variant ('icon', 'avatar', 'smallFeature', 'mediumFeature', 'largeFeature', 'header').
   */
  props = input<Record<string, BoundProperty>>({});
  surfaceId = input<string>();
  componentId = input<string>();
  dataContextPath = input<string>();

  url = computed(() => this.props()['url']?.value());
  description = computed(() => this.props()['description']?.value() || '');
  fit = computed(() => this.props()['fit']?.value() || 'cover');
  variant = computed(() => this.props()['variant']?.value() || 'mediumFeature');
}
