// renderers/react/src/v0_9/catalog/minimal/components/Button.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {z} from 'zod';
import {CommonSchemas} from '@a2ui/web-core/v0_9';

export const ButtonSchema = z.object({
  child: CommonSchemas.ComponentId,
  action: CommonSchemas.Action,
  variant: z.enum(['primary', 'borderless']).optional(),
});

export const ButtonApiDef = {
  name: 'Button',
  schema: ButtonSchema,
};

export const Button = createReactComponent(ButtonApiDef, ({props, buildChild}) => {
  const style: React.CSSProperties = {
    padding: '8px 16px',
    cursor: 'pointer',
    border: props.variant === 'borderless' ? 'none' : '1px solid #ccc',
    backgroundColor: props.variant === 'primary' ? '#007bff' : 'transparent',
    color: props.variant === 'primary' ? '#fff' : 'inherit',
    borderRadius: '4px',
  };

  return (
    <button style={style} onClick={props.action}>
      {props.child ? buildChild(props.child) : null}
    </button>
  );
});

// renderers/angular/src/v0_9/catalog/minimal/button.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ChangeDetectionStrategy, inject, input, computed } from '@angular/core';
import { ComponentHostComponent } from '../../core/component-host.component';
import { DataContext } from '@a2ui/web_core/v0_9';
import { A2uiRendererService } from '../../core/a2ui-renderer.service';
import { BoundProperty } from '../../core/types';

/**
 * Angular implementation of the A2UI Button component (v0.9).
 */
@Component({
  selector: 'a2ui-v09-button',
  imports: [ComponentHostComponent],
  template: `
    <button
      [type]="variant() === 'primary' ? 'submit' : 'button'"
      [class]="'a2ui-button ' + variant()"
      (click)="handleClick()"
    >
      @if (child()) {
        <a2ui-v09-component-host
          [componentId]="child()!"
          [surfaceId]="surfaceId()"
          [dataContextPath]="dataContextPath()"
        >
        </a2ui-v09-component-host>
      }
    </button>
  `,
  styles: [
    `
      .a2ui-button {
        padding: 8px 16px;
        border-radius: 4px;
        border: 1px solid #ccc;
        cursor: pointer;
      }
      .a2ui-button.primary {
        background-color: #007bff;
        color: white;
        border-color: #0069d9;
      }
      .a2ui-button.borderless {
        background: none;
        border: none;
        padding: 0;
        color: #007bff;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  /**
   * Bound properties.
   */
  props = input<Record<string, BoundProperty>>({});
  surfaceId = input.required<string>();
  dataContextPath = input<string>('/');

  private rendererService = inject(A2uiRendererService);

  variant = computed(() => this.props()['variant']?.value() ?? 'default');
  child = computed(() => this.props()['child']?.value());
  action = computed(() => this.props()['action']?.value());

  handleClick() {
    const action = this.action();
    if (action) {
      const surface = this.rendererService.surfaceGroup?.getSurface(this.surfaceId());
      if (surface) {
        const dataContext = new DataContext(surface, this.dataContextPath());
        const resolvedAction = dataContext.resolveAction(action);
        surface.dispatchAction(resolvedAction);
      }
    }
  }
}
