// renderers/react/src/v0_8/components/interactive/MultipleChoice.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useCallback, useId, memo} from 'react';
import type * as Types from '@a2ui/web-core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';

/**
 * MultipleChoice component - a selection component using a dropdown.
 *
 * Renders a <select> element with options, matching the Lit renderer's behavior.
 * Supports two-way data binding for the selected value.
 */
export const MultipleChoice = memo(function MultipleChoice({
  node,
  surfaceId,
}: A2UIComponentProps<Types.MultipleChoiceNode>) {
  const {theme, resolveString, setValue} = useA2UIComponent(node, surfaceId);
  const props = node.properties;
  const id = useId();

  const options =
    (props.options as {label: {literalString?: string; path?: string}; value: string}[]) ?? [];
  const selectionsPath = props.selections?.path;

  // Access description from props (Lit component supports it)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const description = resolveString((props as any).description) ?? 'Select an item';

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      // Two-way binding: update data model with array (matches Lit behavior)
      if (selectionsPath) {
        setValue(selectionsPath, [e.target.value]);
      }
    },
    [selectionsPath, setValue]
  );

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  // Structure mirrors Lit's MultipleChoice component:
  //   <div class="a2ui-multiplechoice">  ← :host equivalent
  //     <section class="...">            ← container theme classes
  //       <label>...</label>             ← description label
  //       <select>...</select>           ← dropdown element
  //     </section>
  //   </div>
  return (
    <div className="a2ui-multiplechoice" style={hostStyle}>
      <section className={classMapToString(theme.components.MultipleChoice.container)}>
        <label htmlFor={id} className={classMapToString(theme.components.MultipleChoice.label)}>
          {description}
        </label>
        <select
          name="data"
          id={id}
          className={classMapToString(theme.components.MultipleChoice.element)}
          style={stylesToObject(theme.additionalStyles?.MultipleChoice)}
          onChange={handleChange}
        >
          {options.map((option) => {
            const label = resolveString(option.label);
            return (
              <option key={option.value} value={option.value}>
                {label}
              </option>
            );
          })}
        </select>
      </section>
    </div>
  );
});

export default MultipleChoice;

// renderers/angular/src/lib/v0_8/components/multiple-choice.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import * as Primitives from '@a2ui/web_core/types/primitives';

@Component({
  selector: 'a2ui-multiple-choice',
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    <section [class]="theme.components.MultipleChoice.container">
      <label [class]="theme.components.MultipleChoice.label" [for]="selectId">{{
        description()
      }}</label>

      <select
        (change)="handleChange($event)"
        [id]="selectId"
        [value]="selectValue()"
        [class]="theme.components.MultipleChoice.element"
        [style]="theme.additionalStyles?.MultipleChoice"
      >
        @for (option of options(); track option.value) {
          <option [value]="option.value">{{ resolvePrimitive(option.label) }}</option>
        }
      </select>
    </section>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
      overflow: auto;
    }

    select {
      width: 100%;
      box-sizing: border-box;
    }
  `,
})
export class MultipleChoice extends DynamicComponent {
  readonly options = input.required<{ label: Primitives.StringValue; value: string }[]>();
  readonly value = input.required<Primitives.StringValue | null>();
  readonly description = input.required<string>();

  protected readonly selectId = super.getUniqueId('a2ui-multiple-choice');
  protected selectValue = computed(() => super.resolvePrimitive(this.value()));

  protected handleChange(event: Event) {
    const path = this.value()?.path;

    if (!(event.target instanceof HTMLSelectElement) || !event.target.value || !path) {
      return;
    }

    const surfaceId = this.surfaceId();
    if (surfaceId) {
      this.processor.setData(
        this.component(),
        path,
        event.target.value,
        surfaceId
      );
    }

  }
}
