// renderers/angular/src/v0_8/components/text.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  ViewEncapsulation,
} from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { DynamicComponent } from '../rendering/dynamic-component';
import * as Primitives from '@a2ui/web-core/types/primitives';
import * as Styles from '@a2ui/web-core/styles/index';
import { Types } from '../types';
import { MarkdownRenderer } from '../data/markdown';

interface HintedStyles {
  h1: Record<string, string>;
  h2: Record<string, string>;
  h3: Record<string, string>;
  h4: Record<string, string>;
  h5: Record<string, string>;
  body: Record<string, string>;
  caption: Record<string, string>;
}

@Component({
  selector: 'a2ui-text',
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    <section
      [class]="classes()"
      [style]="additionalStyles()"
      [innerHTML]="resolvedText() | async"
    ></section>
  `,
  encapsulation: ViewEncapsulation.None,
  imports: [AsyncPipe],
  styles: `
    a2ui-text {
      display: block;
      flex: var(--weight);
    }

    a2ui-text h1,
    a2ui-text h2,
    a2ui-text h3,
    a2ui-text h4,
    a2ui-text h5 {
      line-height: inherit;
      font: inherit;
    }
  `,
})
export class Text extends DynamicComponent<Types.TextNode> {
  private markdownRenderer = inject(MarkdownRenderer);
  readonly text = input.required<Primitives.StringValue | null>();
  readonly usageHint = input<Types.ResolvedText['usageHint'] | null>(null);

  protected resolvedText = computed(() => {
    const usageHint = this.usageHint();
    let value = super.resolvePrimitive(this.text());

    if (value == null) {
      return Promise.resolve('');
    }

    switch (usageHint) {
      case 'h1':
        value = `# ${value}`;
        break;
      case 'h2':
        value = `## ${value}`;
        break;
      case 'h3':
        value = `### ${value}`;
        break;
      case 'h4':
        value = `#### ${value}`;
        break;
      case 'h5':
        value = `##### ${value}`;
        break;
      case 'caption':
        value = `*${value}*`;
        break;
      default:
        value = String(value);
        break;
    }

    return this.markdownRenderer.render(value, {
      tagClassMap: Styles.appendToAll(this.theme.markdown, ['ol', 'ul', 'li'], {}),
    });
  });

  protected classes = computed(() => {
    const usageHint = this.usageHint();

    return Styles.merge(
      this.theme.components.Text.all,
      usageHint ? this.theme.components.Text[usageHint] : {},
    );
  });

  protected additionalStyles = computed(() => {
    const usageHint = this.usageHint();
    const styles = this.theme.additionalStyles?.Text;

    if (!styles) {
      return null;
    }

    let additionalStyles: Record<string, string> = {};

    if (this.areHintedStyles(styles)) {
      additionalStyles = (styles as any)[usageHint ?? 'body'] || {};
    } else if (typeof styles === 'object' && styles !== null) {
      additionalStyles = styles as Record<string, string>;
    }

    return additionalStyles;
  });

  private areHintedStyles(styles: unknown): styles is HintedStyles {
    if (typeof styles !== 'object' || !styles || Array.isArray(styles)) {
      return false;
    }

    const expected = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'caption', 'body'];
    return expected.every((v) => v in styles);
  }
}

// renderers/lit/src/0.8/ui/text.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, css, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { markdown } from "./directives/directives.js";
import { Root } from "./root.js";
import { A2uiMessageProcessor } from "@a2ui/web-core/data/model-processor";
import * as Primitives from "@a2ui/web-core/types/primitives";
import * as Types from "@a2ui/web-core/types/types";
import * as Context from "./context/context.js";
import { consume } from "@lit/context";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import { structuralStyles } from "./styles.js";
import { Styles } from "../index.js";

interface HintedStyles {
  h1: Record<string, string>;
  h2: Record<string, string>;
  h3: Record<string, string>;
  h4: Record<string, string>;
  h5: Record<string, string>;
  body: Record<string, string>;
  caption: Record<string, string>;
}

@customElement("a2ui-text")
export class Text extends Root {
  @property()
  accessor text: Primitives.StringValue | null = null;

  @property({ reflect: true, attribute: "usage-hint" })
  accessor usageHint: Types.ResolvedText["usageHint"] | null = null;

  // Allow users to specify their own markdown renderer,
  // or the one provided by @a2ui/markdown-it.
  @consume({context: Context.markdown})
  accessor markdownRenderer: Types.MarkdownRenderer | undefined = undefined;

  static styles = [
    structuralStyles,
    css`
      :host {
        display: block;
        flex: var(--weight);
      }

      h1,
      h2,
      h3,
      h4,
      h5 {
        line-height: inherit;
        font: inherit;
      }
    `,
  ];

  #renderText() {
    let textValue: string | null | undefined = null;

    if (this.text && typeof this.text === "object") {
      if ("literalString" in this.text && this.text.literalString) {
        textValue = this.text.literalString;
      } else if ("literal" in this.text && this.text.literal !== undefined) {
        textValue = this.text.literal;
      } else if (this.text && "path" in this.text && this.text.path) {
        if (!this.processor || !this.component) {
          return html`(no model)`;
        }

        const value = this.processor.getData(
          this.component,
          this.text.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID
        );

        if (value !== null && value !== undefined) {
          textValue = value.toString();
        }
      }
    }

    if (textValue === null || textValue === undefined) {
      return html`(empty)`;
    }

    let markdownText = textValue;
    switch (this.usageHint) {
      case "h1":
        markdownText = `# ${markdownText}`;
        break;
      case "h2":
        markdownText = `## ${markdownText}`;
        break;
      case "h3":
        markdownText = `### ${markdownText}`;
        break;
      case "h4":
        markdownText = `#### ${markdownText}`;
        break;
      case "h5":
        markdownText = `##### ${markdownText}`;
        break;
      case "caption":
        markdownText = `*${markdownText}*`;
        break;
      default:
        break; // Body.
    }

    return html`${markdown(
      markdownText,
      this.markdownRenderer, {
        tagClassMap: Styles.appendToAll(this.theme.markdown, ["ol", "ul", "li"], {})
      },
    )}`;
  }

  #areHintedStyles(styles: unknown): styles is HintedStyles {
    if (typeof styles !== "object") return false;
    if (Array.isArray(styles)) return false;
    if (!styles) return false;

    const expected = ["h1", "h2", "h3", "h4", "h5", "h6", "caption", "body"];
    return expected.every((v) => v in styles);
  }

  #getAdditionalStyles() {
    let additionalStyles: Record<string, string> = {};
    const styles = this.theme.additionalStyles?.Text;
    if (!styles) return additionalStyles;

    if (this.#areHintedStyles(styles)) {
      const hint = this.usageHint ?? "body";
      additionalStyles = styles[hint] as Record<string, string>;
    } else {
      additionalStyles = styles;
    }

    return additionalStyles;
  }

  render() {
    const classes = Styles.merge(
      this.theme.components.Text.all,
      this.usageHint ? this.theme.components.Text[this.usageHint] : {}
    );

    return html`<section
      class=${classMap(classes)}
      style=${this.theme.additionalStyles?.Text
        ? styleMap(this.#getAdditionalStyles())
        : nothing}
    >
      ${this.#renderText()}
    </section>`;
  }
}
