// renderers/react/src/v0_9/catalog/basic/components/Card.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {CardApi} from '@a2ui/web-core/v0_9/basic_catalog';
import {getBaseContainerStyle} from '../utils';

export const Card = createReactComponent(CardApi, ({props, buildChild}) => {
  const style: React.CSSProperties = {
    ...getBaseContainerStyle(),
    backgroundColor: '#fff',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    width: '100%',
  };

  return <div style={style}>{props.child ? buildChild(props.child) : null}</div>;
});

// renderers/angular/a2ui_explorer/src/app/card.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ChangeDetectionStrategy, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentHostComponent } from '@a2ui/angular/v0_9';
import { ResolveA2uiProps } from '@a2ui/web_core/v0_9';
import { DemoCardApiType } from './demo-catalog';

/**
 * A simple card component for the demo.
 */
@Component({
  selector: 'demo-card',
  standalone: true,
  imports: [CommonModule, ComponentHostComponent],
  template: `
    <div
      class="demo-card"
      style="border: 1px solid #ccc; padding: 16px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 16px; background-color: white;"
    >
      @if (props().child) {
        <a2ui-v09-component-host
          [componentId]="props().child!"
          [surfaceId]="surfaceId()"
        >
        </a2ui-v09-component-host>
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent {
  props = input.required<ResolveA2uiProps<DemoCardApiType>>();
  surfaceId = input.required<string>();
}
